"use client";

import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import type { ContentStudioRecord } from "@/lib/content-studio";

type Tone = "Sharp" | "Founder" | "Educational" | "Viral";
type Platform = "X" | "Instagram Carousel" | "TikTok Script" | "LinkedIn";
type CtaLevel = "Auto" | "Soft" | "Medium" | "Direct";
type ContentPattern =
  | "Contrarian"
  | "Founder note"
  | "Educational"
  | "Hot take"
  | "Case breakdown"
  | "Build-after-replies"
  | "Tiny offer";
type QualityField =
  | "hook"
  | "buyerSpecificity"
  | "paidPain"
  | "tinyOffer"
  | "cta";
type ReadinessStatus = "Ready" | "Needs Work" | "Skip";
type PerformanceStatus = "winner" | "maybe" | "loser" | "";
type StatusFilter = "All" | ReadinessStatus;
type AssetKind =
  | "X post"
  | "X thread"
  | "3-slide carousel"
  | "5-slide carousel"
  | "TikTok 15s script"
  | "LinkedIn post";

type GeneratedAsset = {
  kind: AssetKind;
  body: string;
};

type GeneratedCard = {
  id: string;
  contentType: AssetKind;
  ctaStyle: CtaLevel;
  hookStyle: ContentPattern;
  record: ContentStudioRecord;
  assets: GeneratedAsset[];
  quality: QualityScores;
};

type CardState = {
  clicks?: number;
  contentType?: AssetKind;
  hookStyle?: ContentPattern;
  impressions?: number;
  improvementCount?: number;
  likes?: number;
  loserRewrite?: string;
  nextAngle?: string;
  note: string;
  posted: boolean;
  platform?: Platform;
  replies?: number;
  status?: PerformanceStatus;
  ctaStyle?: CtaLevel;
  variations?: string[];
  winner?: PerformanceStatus;
};

type StoredState = Record<string, CardState>;

type QualityScores = {
  buyerSpecificity: number;
  cta: number;
  hook: number;
  lowestField: QualityField;
  overall: number;
  paidPain: number;
  readiness: ReadinessStatus;
  tinyOffer: number;
};

const storageKey = "bilion-content-studio-awareness-v1";
const tones = ["Sharp", "Founder", "Educational", "Viral"] as const;
const platforms = ["X", "Instagram Carousel", "TikTok Script", "LinkedIn"] as const;
const ctaLevels = ["Auto", "Soft", "Medium", "Direct"] as const;

const ctaCopy: Record<CtaLevel, string> = {
  Auto: "Generated by Bilion.",
  Soft: "Generated by Bilion",
  Medium: "Get the full Build/Sell/Post pack inside Bilion",
  Direct: "Find your next AI business signal with Bilion",
};

const ctaVariants = [
  "Generated by Bilion.",
  "Generated by Bilion. Find the full Build/Sell/Post pack inside.",
  "One of today's 30 money moves from Bilion.",
  "Get the full Codex prompt inside Bilion.",
];

const contentPatterns: ContentPattern[] = [
  "Contrarian",
  "Founder note",
  "Educational",
  "Hot take",
  "Case breakdown",
  "Build-after-replies",
  "Tiny offer",
];

const hookBank = [
  "Stop building random AI apps.",
  "This boring workflow could become a $199 offer.",
  "Someone is already paying for this pain.",
  "AI builders do not need more ideas. They need money moves.",
  "This is the kind of AI business I would test before building.",
  "The best AI ideas usually start as annoying manual work.",
  "Before you build the app, find the paid pain.",
  "A tiny offer is hiding inside this workflow.",
];

const snsVisibleFields = [
  "Money Move",
  "Buyer",
  "Paid Pain",
  "Tiny Offer",
  "Price",
  "Generated by Bilion CTA",
];

const bilionDeepDiveFields = [
  "Build it",
  "Sell it",
  "Post it",
  "Codex prompt",
  "Validation plan",
  "Objections",
  "DM script",
  "Carousel copy",
  "Landing page angle",
  "Pricing ladder",
  "Risks",
  "Similar pattern",
];

const platformAsset: Record<Platform, AssetKind> = {
  X: "X post",
  "Instagram Carousel": "3-slide carousel",
  "TikTok Script": "TikTok 15s script",
  LinkedIn: "LinkedIn post",
};

const qualityLabels: Record<QualityField, string> = {
  buyerSpecificity: "Buyer specificity",
  cta: "CTA",
  hook: "Hook",
  paidPain: "Paid pain",
  tinyOffer: "Tiny offer",
};

function compact(value: string, maxLength = 180) {
  const cleanValue = value.replace(/\s+/g, " ").trim();

  if (cleanValue.length <= maxLength) {
    return cleanValue;
  }

  const sentence = cleanValue
    .split(/(?<=[.!?])\s+/)
    .find((item) => item.length > 24 && item.length <= maxLength);

  if (sentence) {
    return sentence;
  }

  const words = cleanValue.split(" ");
  let nextValue = "";

  for (const word of words) {
    const candidate = nextValue ? `${nextValue} ${word}` : word;

    if (candidate.length > maxLength) {
      break;
    }

    nextValue = candidate;
  }

  return nextValue || cleanValue.slice(0, maxLength).trim();
}

function scoreTextSpecificity(value: string, goodLength: number) {
  const cleanValue = value.trim();
  let score = 4;

  if (cleanValue.length >= goodLength) {
    score += 2;
  }

  if (/\d|\$|USD|JPY|month|week|daily|hour|client|owner|operator/i.test(cleanValue)) {
    score += 1.5;
  }

  if (/,| and | with | for | at /i.test(cleanValue)) {
    score += 1;
  }

  if (/not extracted|generic|someone|people|users/i.test(cleanValue)) {
    score -= 1.5;
  }

  return Math.max(1, Math.min(10, Math.round(score)));
}

function scoreHook(body: string) {
  const [firstLine = ""] = body.split("\n");
  let score = 4;

  if (firstLine.length >= 28 && firstLine.length <= 120) {
    score += 2;
  }

  if (/stop|boring|paying|paid|random|before building|tiny|money move|test/i.test(firstLine)) {
    score += 2;
  }

  if (firstLine.includes("?") || firstLine.includes(":")) {
    score += 0.5;
  }

  if (/Money Move:/i.test(firstLine)) {
    score -= 3;
  }

  return Math.max(1, Math.min(10, Math.round(score)));
}

function scoreCta(body: string) {
  const ctaLine = body.split("\n").slice(-2).join(" ");
  let score = 4;

  if (/Bilion/i.test(ctaLine)) {
    score += 2;
  }

  if (/Build\/Sell\/Post|Codex|money moves|signal/i.test(ctaLine)) {
    score += 2;
  }

  if (ctaLine.length >= 18 && ctaLine.length <= 95) {
    score += 1;
  }

  return Math.max(1, Math.min(10, Math.round(score)));
}

function getReadiness(overall: number): ReadinessStatus {
  if (overall >= 8) {
    return "Ready";
  }

  if (overall >= 6) {
    return "Needs Work";
  }

  return "Skip";
}

function getQualityScores(record: ContentStudioRecord, body: string): QualityScores {
  const scores = {
    buyerSpecificity: scoreTextSpecificity(record.buyer, 65),
    cta: scoreCta(body),
    hook: scoreHook(body),
    paidPain: scoreTextSpecificity(record.pain, 85),
    tinyOffer: scoreTextSpecificity(`${record.firstProduct} ${record.price}`, 55),
  };
  const entries = Object.entries(scores) as Array<[QualityField, number]>;
  const [lowestField] = entries.reduce((lowest, entry) =>
    entry[1] < lowest[1] ? entry : lowest,
  );
  const overall =
    Math.round(
      (scores.hook +
        scores.buyerSpecificity +
        scores.paidPain +
        scores.tinyOffer +
        scores.cta) *
        2,
    ) / 10;

  return {
    ...scores,
    lowestField,
    overall,
    readiness: getReadiness(overall),
  };
}

function classifyPerformance(state: CardState): PerformanceStatus {
  const clicks = state.clicks || 0;
  const impressions = state.impressions || 0;
  const likes = state.likes || 0;
  const replies = state.replies || 0;

  if (replies > 0 || clicks > 0) {
    return "winner";
  }

  if (impressions >= 500 && likes + replies + clicks <= 2) {
    return "maybe";
  }

  if (impressions > 0 && impressions < 500 && likes + replies + clicks === 0) {
    return "loser";
  }

  return state.status || state.winner || "";
}

function getDefaultCardState(card: GeneratedCard, platform: Platform): CardState {
  return {
    clicks: 0,
    contentType: card.contentType,
    ctaStyle: card.ctaStyle,
    hookStyle: card.hookStyle,
    impressions: 0,
    improvementCount: 0,
    likes: 0,
    nextAngle: "",
    note: "",
    platform,
    posted: false,
    replies: 0,
    status: "",
    winner: "",
  };
}

function pickByIndex<T>(items: readonly T[], index: number) {
  return items[index % items.length];
}

function getCta(ctaLevel: CtaLevel, index: number) {
  if (ctaLevel === "Auto") {
    return pickByIndex(ctaVariants, index);
  }

  return ctaCopy[ctaLevel].endsWith(".") ? ctaCopy[ctaLevel] : `${ctaCopy[ctaLevel]}.`;
}

function withCta(body: string, ctaLevel: CtaLevel, index: number) {
  return `${body}\n\n${getCta(ctaLevel, index)}`;
}

function getPattern(index: number) {
  return pickByIndex(contentPatterns, index);
}

function getHook(record: ContentStudioRecord, tone: Tone, index: number) {
  if (tone === "Founder") {
    return pickByIndex(
      [
        "This is the kind of AI business I would test before building.",
        "If I had one weekend, I would not start with the app. I would test this pain.",
        "I would rather sell this tiny offer than spend a month building blind.",
      ],
      index,
    );
  }

  if (tone === "Educational") {
    return pickByIndex(
      [
        "Here is how to spot a real AI business signal.",
        "A money move has a buyer, a pain, and a small paid next step.",
        "This is what a buildable AI opportunity looks like before the product exists.",
      ],
      index,
    );
  }

  if (tone === "Viral") {
    return pickByIndex(
      [
        "Someone is already paying for this pain.",
        "This boring workflow could become a $199 offer.",
        "Most people miss this because it does not look like a startup idea.",
      ],
      index,
    );
  }

  if (index % 5 === 0) {
    return `Stop building random AI apps for ${compact(record.buyer, 70)}.`;
  }

  return pickByIndex(hookBank, index);
}

function buildXPost(
  record: ContentStudioRecord,
  tone: Tone,
  ctaLevel: CtaLevel,
  index: number,
) {
  const hook = getHook(record, tone, index);
  const pattern = getPattern(index);
  const buyer = compact(record.buyer, 105);
  const pain = compact(record.pain, 135);
  const moneyMove = compact(record.productIdea, 110);
  const tinyOffer = compact(record.firstProduct, 110);
  const price = compact(record.price, 70);

  const bodies: Record<ContentPattern, string> = {
    Contrarian: [
      hook,
      "",
      `The opportunity is not another AI wrapper. It is ${moneyMove}.`,
      `${buyer} already feel the pain: ${pain}`,
      "",
      `Tiny offer: ${tinyOffer}`,
      `Price angle: ${price}`,
    ].join("\n"),
    "Founder note": [
      hook,
      "",
      `I would look for replies from ${buyer} before writing code.`,
      `The pain: ${pain}`,
      "",
      `First test: sell ${tinyOffer} around ${price}.`,
    ].join("\n"),
    Educational: [
      hook,
      "",
      `Money move: ${moneyMove}`,
      `Buyer: ${buyer}`,
      `Paid pain: ${pain}`,
      "",
      `Smallest offer: ${tinyOffer}`,
      `Price: ${price}`,
    ].join("\n"),
    "Hot take": [
      hook,
      "",
      `The product idea matters less than the paid pain.`,
      `${buyer} do not need a huge platform. They need help with: ${pain}`,
      "",
      `That can start as ${tinyOffer}.`,
    ].join("\n"),
    "Case breakdown": [
      hook,
      "",
      `Case: ${moneyMove}`,
      `Who pays: ${buyer}`,
      `Why now: ${pain}`,
      "",
      `Tiny offer to test: ${tinyOffer}`,
      `Price: ${price}`,
    ].join("\n"),
    "Build-after-replies": [
      hook,
      "",
      `Do not build this first.`,
      `Post the pain, DM ${buyer}, and wait for replies.`,
      "",
      `If they confirm "${pain}", then test ${tinyOffer}.`,
    ].join("\n"),
    "Tiny offer": [
      hook,
      "",
      `Buyer: ${buyer}`,
      `Pain: ${pain}`,
      "",
      `Tiny offer: ${tinyOffer}`,
      `Price: ${price}`,
      "",
      `That is enough to test before building software.`,
    ].join("\n"),
  };

  return withCta(bodies[pattern], ctaLevel, index);
}

function buildXThread(
  record: ContentStudioRecord,
  tone: Tone,
  ctaLevel: CtaLevel,
  index: number,
) {
  return withCta(
    [
      `1/ ${getHook(record, tone, index)}`,
      "",
      `2/ The money move:\n${compact(record.productIdea, 150)}`,
      "",
      `3/ The buyer:\n${compact(record.buyer, 145)}`,
      "",
      `4/ The pain they would pay to remove:\n${compact(record.pain, 160)}`,
      "",
      `5/ The tiny offer:\n${compact(record.firstProduct, 140)}`,
      "",
      `6/ Price angle:\n${compact(record.price, 90)}`,
    ].join("\n"),
    ctaLevel,
    index,
  );
}

function buildThreeSlideCarousel(
  record: ContentStudioRecord,
  tone: Tone,
  ctaLevel: CtaLevel,
  index: number,
) {
  return withCta(
    [
      `Slide 1: ${getHook(record, tone, index)}`,
      `Slide 2: Who pays and why\n${compact(record.buyer, 95)}\n${compact(record.pain, 115)}`,
      `Slide 3: Tiny offer to test\n${compact(record.firstProduct, 115)}\n${compact(record.price, 75)}`,
    ].join("\n\n"),
    ctaLevel,
    index,
  );
}

function buildFiveSlideCarousel(
  record: ContentStudioRecord,
  tone: Tone,
  ctaLevel: CtaLevel,
  index: number,
) {
  return withCta(
    [
      `Slide 1: ${getHook(record, tone, index)}`,
      `Slide 2: The money move\n${compact(record.productIdea, 120)}`,
      `Slide 3: The buyer\n${compact(record.buyer, 120)}`,
      `Slide 4: The paid pain\n${compact(record.pain, 135)}`,
      `Slide 5: The tiny offer\n${compact(record.firstProduct, 105)}\n${compact(record.price, 75)}`,
    ].join("\n\n"),
    ctaLevel,
    index,
  );
}

function buildTikTokScript(
  record: ContentStudioRecord,
  tone: Tone,
  ctaLevel: CtaLevel,
  index: number,
) {
  return withCta(
    [
      "Hook:",
      getHook(record, tone, index),
      "",
      "Say:",
      `${compact(record.buyer, 70)} have this annoying paid pain: ${compact(record.pain, 90)}`,
      "",
      "Close:",
      `I would test ${compact(record.firstProduct, 80)} before building the app.`,
    ].join("\n"),
    ctaLevel,
    index,
  );
}

function buildLinkedIn(
  record: ContentStudioRecord,
  tone: Tone,
  ctaLevel: CtaLevel,
  index: number,
) {
  return withCta(
    [
      getHook(record, tone, index),
      "",
      `The money move is ${compact(record.productIdea, 135)}.`,
      "",
      `${compact(record.buyer, 120)} have a specific paid pain: ${compact(record.pain, 150)}`,
      "",
      `The first offer does not need to be big: ${compact(record.firstProduct, 130)}`,
      `Price angle: ${compact(record.price, 85)}`,
      "",
      "The deep work is deciding what to build, how to sell it, and what to post next.",
    ].join("\n"),
    ctaLevel,
    index,
  );
}

function buildImprovedXPost(
  card: GeneratedCard,
  focus: QualityField,
  attempt: number,
) {
  const record = card.record;
  const buyer = compact(record.buyer, focus === "buyerSpecificity" ? 135 : 105);
  const pain = compact(record.pain, focus === "paidPain" ? 165 : 125);
  const moneyMove = compact(record.productIdea, 110);
  const tinyOffer = compact(record.firstProduct, focus === "tinyOffer" ? 145 : 105);
  const price = compact(record.price, 70);
  const hook = pickByIndex(
    [
      "Someone is already paying for this pain.",
      "This is the kind of boring workflow I would test first.",
      "Stop guessing. Start with the money move.",
      "A tiny AI offer is hiding inside this manual workflow.",
    ],
    attempt,
  );
  const cta =
    focus === "cta"
      ? "Get the full Build/Sell/Post pack inside Bilion."
      : getCta(card.ctaStyle, attempt);

  const focusLine: Record<QualityField, string> = {
    buyerSpecificity: `Specific buyer: ${buyer}`,
    cta: `Bilion can turn this into the full Build/Sell/Post path.`,
    hook: `The signal: ${moneyMove}`,
    paidPain: `Paid pain: ${pain}`,
    tinyOffer: `Tiny offer: ${tinyOffer} at ${price}`,
  };

  return [
    hook,
    "",
    focusLine[focus],
    focus === "buyerSpecificity" ? `Pain: ${pain}` : `Buyer: ${buyer}`,
    focus === "tinyOffer" ? "" : `Tiny offer: ${tinyOffer}`,
    `Price angle: ${price}`,
    "",
    cta,
  ]
    .filter((line) => line !== "")
    .join("\n");
}

function buildWinnerVariations(card: GeneratedCard) {
  const record = card.record;
  const buyer = compact(record.buyer, 105);
  const pain = compact(record.pain, 130);
  const offer = compact(record.firstProduct, 105);
  const price = compact(record.price, 70);

  return [
    [
      "Stronger hook version",
      "",
      "Someone is already paying to make this pain disappear.",
      `${buyer} struggle with: ${pain}`,
      `Tiny offer: ${offer}`,
      `Price: ${price}`,
      "",
      "Generated by Bilion. Find the full Build/Sell/Post pack inside.",
    ].join("\n"),
    [
      "Carousel-first version",
      "",
      "Slide 1: Stop building random AI apps.",
      `Slide 2: Buyer\n${buyer}`,
      `Slide 3: Paid pain\n${pain}`,
      `Slide 4: Tiny offer\n${offer}`,
      `Slide 5: Price + CTA\n${price}\nGenerated by Bilion.`,
    ].join("\n"),
    [
      "Direct CTA version",
      "",
      "This is the kind of AI business signal worth testing before building.",
      `Buyer: ${buyer}`,
      `Pain: ${pain}`,
      `Offer: ${offer}`,
      "",
      "Find your next AI business signal with Bilion.",
    ].join("\n"),
  ];
}

function buildLoserRewrite(card: GeneratedCard, attempt: number) {
  const record = card.record;
  const original = card.assets.find((asset) => asset.kind === "X post")?.body || "";
  const [, ...rest] = original.split("\n");
  const newHook = pickByIndex(
    [
      "This did not need a bigger app. It needed a sharper paid pain.",
      "The hook is the business: who pays, and what hurts right now?",
      "This AI idea gets clearer when you stop talking about the tool.",
    ],
    attempt,
  );

  return [
    newHook,
    ...rest.filter((line) => !/^Generated by Bilion/i.test(line)),
    "",
    `Buyer: ${compact(record.buyer, 100)}`,
    "Generated by Bilion.",
  ].join("\n");
}

function buildAssets(
  record: ContentStudioRecord,
  tone: Tone,
  ctaLevel: CtaLevel,
  index: number,
): GeneratedAsset[] {
  return [
    { kind: "X post", body: buildXPost(record, tone, ctaLevel, index) },
    { kind: "X thread", body: buildXThread(record, tone, ctaLevel, index) },
    {
      kind: "3-slide carousel",
      body: buildThreeSlideCarousel(record, tone, ctaLevel, index),
    },
    {
      kind: "5-slide carousel",
      body: buildFiveSlideCarousel(record, tone, ctaLevel, index),
    },
    {
      kind: "TikTok 15s script",
      body: buildTikTokScript(record, tone, ctaLevel, index),
    },
    { kind: "LinkedIn post", body: buildLinkedIn(record, tone, ctaLevel, index) },
  ];
}

function generateCards(
  records: ContentStudioRecord[],
  tone: Tone,
  ctaLevel: CtaLevel,
): GeneratedCard[] {
  return records.slice(0, 30).map((record, index) => {
    const assets = buildAssets(record, tone, ctaLevel, index);
    const primaryBody =
      assets.find((asset) => asset.kind === "X post")?.body || assets[0].body;

    return {
      id: `${record.id}-${tone}-${ctaLevel}`,
      contentType: "X post",
      ctaStyle: ctaLevel,
      hookStyle: getPattern(index),
      record,
      assets,
      quality: getQualityScores(record, primaryBody),
    };
  });
}

function buildMarkdownExport(
  cards: GeneratedCard[],
  cardStates: StoredState,
  selectedAssetKind: AssetKind,
) {
  const body = cards
    .map((card, index) => {
      const state = cardStates[card.record.id] || { note: "", posted: false };
      const assets = card.assets
        .map((asset) => [`### ${asset.kind}`, "", asset.body].join("\n"))
        .join("\n\n");

      return [
        `## ${index + 1}. ${card.record.title}`,
        "",
        `Source: ${card.record.sourceType}`,
        `Primary channel asset: ${selectedAssetKind}`,
        `Posted: ${state.posted ? "yes" : "no"}`,
        state.note ? `Reaction note: ${state.note}` : "Reaction note:",
        "",
        assets,
      ].join("\n");
    })
    .join("\n\n---\n\n");

  return [
    "# Bilion Operator Awareness Pack",
    "",
    "Internal marketing export. Not a customer-facing product feature.",
    `Primary channel asset: ${selectedAssetKind}`,
    `Records: ${cards.length}`,
    "",
    body,
  ].join("\n");
}

function buildChannelQueueExport(
  cards: GeneratedCard[],
  cardStates: StoredState,
  selectedAssetKind: AssetKind,
) {
  const body = cards
    .map((card, index) => {
      const state = cardStates[card.record.id] || { note: "", posted: false };
      const asset = card.assets.find((item) => item.kind === selectedAssetKind);

      return [
        `## ${index + 1}. ${card.record.title}`,
        "",
        `Source: ${card.record.sourceType}`,
        `Asset: ${selectedAssetKind}`,
        `Posted: ${state.posted ? "yes" : "no"}`,
        state.note ? `Reaction note: ${state.note}` : "Reaction note:",
        "",
        asset?.body || card.assets[0].body,
      ].join("\n");
    })
    .join("\n\n---\n\n");

  return [
    "# Bilion Today's 30 Posting Queue",
    "",
    "Internal marketing export. Copy these into the selected social channel.",
    `Asset: ${selectedAssetKind}`,
    `Records: ${cards.length}`,
    "",
    body,
  ].join("\n");
}

function readStoredState(): StoredState {
  if (typeof window === "undefined") {
    return {};
  }

  try {
    const rawValue = window.localStorage.getItem(storageKey);

    if (!rawValue) {
      return {};
    }

    const parsed = JSON.parse(rawValue) as unknown;

    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      return {};
    }

    return parsed as StoredState;
  } catch {
    return {};
  }
}

async function copyText(value: string) {
  try {
    await navigator.clipboard.writeText(value);

    return true;
  } catch {
    return false;
  }
}

export default function ContentStudioClient({
  records,
}: {
  records: ContentStudioRecord[];
}) {
  const [tone, setTone] = useState<Tone>("Sharp");
  const [platform, setPlatform] = useState<Platform>("X");
  const [ctaLevel, setCtaLevel] = useState<CtaLevel>("Auto");
  const [statusFilter, setStatusFilter] = useState<StatusFilter>("All");
  const [cardStates, setCardStates] = useState<StoredState>(() =>
    readStoredState(),
  );
  const [cards, setCards] = useState<GeneratedCard[]>(() =>
    generateCards(records, "Sharp", "Auto"),
  );
  const [copiedKey, setCopiedKey] = useState("");

  const selectedAssetKind = platformAsset[platform];
  const markdownExport = useMemo(
    () => buildMarkdownExport(cards, cardStates, selectedAssetKind),
    [cards, cardStates, selectedAssetKind],
  );
  const channelQueueExport = useMemo(
    () => buildChannelQueueExport(cards, cardStates, selectedAssetKind),
    [cards, cardStates, selectedAssetKind],
  );
  const visibleCards =
    statusFilter === "All"
      ? cards
      : cards.filter((card) => card.quality.readiness === statusFilter);
  const postedCount = cards.filter((card) => cardStates[card.record.id]?.posted).length;
  const summary = {
    generated: cards.length,
    losers: cards.filter(
      (card) => classifyPerformance(cardStates[card.record.id] || getDefaultCardState(card, platform)) === "loser",
    ).length,
    needsWork: cards.filter((card) => card.quality.readiness === "Needs Work").length,
    posted: postedCount,
    ready: cards.filter((card) => card.quality.readiness === "Ready").length,
    winners: cards.filter(
      (card) => classifyPerformance(cardStates[card.record.id] || getDefaultCardState(card, platform)) === "winner",
    ).length,
  };
  const sourceCounts = useMemo(
    () =>
      records.reduce<Record<string, number>>((counts, record) => {
        counts[record.sourceType] = (counts[record.sourceType] || 0) + 1;

        return counts;
      }, {}),
    [records],
  );

  useEffect(() => {
    window.localStorage.setItem(storageKey, JSON.stringify(cardStates));
  }, [cardStates]);

  function handleGenerate() {
    const nextCards = generateCards(records, tone, ctaLevel);
    setCards(nextCards);
    setCardStates((current) => {
      const nextState = { ...current };

      for (const card of nextCards) {
        const currentState = nextState[card.record.id] || getDefaultCardState(card, platform);
        nextState[card.record.id] = {
          ...currentState,
          contentType: card.contentType,
          ctaStyle: card.ctaStyle,
          hookStyle: card.hookStyle,
          platform,
        };
      }

      return nextState;
    });
  }

  function handlePlatformChange(nextPlatform: Platform) {
    setPlatform(nextPlatform);
    setCardStates((current) => {
      const nextState = { ...current };

      for (const card of cards) {
        nextState[card.record.id] = {
          ...(nextState[card.record.id] || getDefaultCardState(card, nextPlatform)),
          contentType: platformAsset[nextPlatform],
          platform: nextPlatform,
        };
      }

      return nextState;
    });
  }

  function handleCtaChange(nextCtaLevel: CtaLevel) {
    setCtaLevel(nextCtaLevel);
    setCardStates((current) => {
      const nextState = { ...current };

      for (const card of cards) {
        nextState[card.record.id] = {
          ...(nextState[card.record.id] || getDefaultCardState(card, platform)),
          ctaStyle: nextCtaLevel,
        };
      }

      return nextState;
    });
  }

  function updateCardState(recordId: string, nextState: Partial<CardState>) {
    setCardStates((current) => {
      const currentState = current[recordId] || { note: "", posted: false };

      return {
        ...current,
        [recordId]: {
          ...currentState,
          ...nextState,
        },
      };
    });
  }

  async function handleCopy(key: string, body: string) {
    const didCopy = await copyText(body);
    setCopiedKey(didCopy ? key : "error");
    window.setTimeout(() => setCopiedKey(""), 1400);
  }

  function handleImprove(card: GeneratedCard) {
    const currentState = cardStates[card.record.id] || getDefaultCardState(card, platform);
    const improvementCount = currentState.improvementCount || 0;

    if (improvementCount >= 3) {
      return;
    }

    const improvedBody = buildImprovedXPost(
      card,
      card.quality.lowestField,
      improvementCount + 1,
    );
    const improvedAssets = card.assets.map((asset) =>
      asset.kind === "X post" ? { ...asset, body: improvedBody } : asset,
    );
    const improvedQuality = getQualityScores(card.record, improvedBody);

    setCards((current) =>
      current.map((item) =>
        item.id === card.id
          ? {
              ...item,
              assets: improvedAssets,
              quality:
                improvementCount + 1 >= 3 && improvedQuality.overall < 8
                  ? { ...improvedQuality, readiness: "Skip" }
                  : improvedQuality,
            }
          : item,
      ),
    );
    updateCardState(card.record.id, {
      improvementCount: improvementCount + 1,
      nextAngle: `Improved ${qualityLabels[card.quality.lowestField]}`,
    });
  }

  function handleMakeVariations(card: GeneratedCard) {
    updateCardState(card.record.id, {
      variations: buildWinnerVariations(card),
    });
  }

  function handleRewriteHook(card: GeneratedCard) {
    const currentState = cardStates[card.record.id] || getDefaultCardState(card, platform);
    updateCardState(card.record.id, {
      loserRewrite: buildLoserRewrite(card, currentState.improvementCount || 0),
      nextAngle: "Rewrite hook and retest with the same signal",
    });
  }

  return (
    <main className="min-h-screen bg-zinc-950 px-4 py-6 text-zinc-100 sm:px-6 lg:px-8">
      <div className="mx-auto flex w-full max-w-7xl flex-col gap-6">
        <section className="border-b border-white/10 pb-6">
          <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
            <div className="min-w-0">
              <div className="text-xs font-black uppercase tracking-[0.16em] text-emerald-300">
                Operator / Internal Marketing / Loop Engine
              </div>
              <h1 className="mt-3 max-w-3xl text-3xl font-black tracking-tight text-white sm:text-5xl">
                Bilion awareness pack from internal DB records.
              </h1>
              <p className="mt-4 max-w-3xl text-sm leading-6 text-zinc-400 sm:text-base">
                Internal operator page for turning existing Bilion signals into
                social awareness posts. Bilion customer-facing value stays
                Build / Sell / Post. This page is not an LP feature, paid
                feature, or user-facing product promise.
              </p>
              <div className="mt-4 grid max-w-4xl gap-3 text-xs leading-5 text-zinc-400 md:grid-cols-2">
                <InfoPanel
                  label="SNS shows"
                  items={snsVisibleFields}
                />
                <InfoPanel
                  label="Bilion deep dive keeps"
                  items={bilionDeepDiveFields}
                />
              </div>
            </div>

            <div className="grid gap-2 text-sm text-zinc-400 sm:grid-cols-3 lg:w-[28rem]">
              {Object.entries(sourceCounts).map(([label, count]) => (
                <div
                  key={label}
                  className="rounded-lg border border-white/10 bg-white/[0.03] p-3"
                >
                  <div className="text-xl font-black text-white">{count}</div>
                  <div className="mt-1 capitalize">{label}s</div>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="grid gap-4 rounded-lg border border-white/10 bg-white/[0.03] p-4 xl:grid-cols-[1fr_1fr_1fr_auto] xl:items-end">
          <ControlGroup label="Tone">
            {tones.map((item) => (
              <ToggleButton
                key={item}
                active={tone === item}
                label={item}
                onClick={() => setTone(item)}
              />
            ))}
          </ControlGroup>

          <ControlGroup label="Platform">
            {platforms.map((item) => (
              <ToggleButton
                key={item}
                active={platform === item}
                label={item}
                onClick={() => handlePlatformChange(item)}
              />
            ))}
          </ControlGroup>

          <ControlGroup label="CTA">
            {ctaLevels.map((item) => (
              <ToggleButton
                key={item}
                active={ctaLevel === item}
                label={item}
                onClick={() => handleCtaChange(item)}
              />
            ))}
          </ControlGroup>

          <div className="grid gap-2 xl:w-80">
            <button
              type="button"
              onClick={handleGenerate}
              className="min-h-12 rounded-md bg-white px-5 text-sm font-black text-zinc-950 transition hover:bg-zinc-200"
            >
              Generate Daily Content Mix
            </button>
            <button
              type="button"
              onClick={() => void handleCopy("channel-export", channelQueueExport)}
              className="min-h-12 rounded-md bg-emerald-300 px-5 text-sm font-black text-zinc-950 transition hover:bg-emerald-200"
            >
              {copiedKey === "channel-export"
                ? "Copied"
                : `1-click Copy ${platform}`}
            </button>
            <button
              type="button"
              onClick={() => void handleCopy("markdown-export", markdownExport)}
              className="min-h-12 rounded-md border border-white/10 px-5 text-sm font-black text-zinc-100 transition hover:bg-white/[0.06]"
            >
              {copiedKey === "markdown-export"
                ? "Copied"
                : "Export Today's 30 as Markdown"}
            </button>
          </div>
        </section>

        <section className="grid gap-3 rounded-lg border border-white/10 bg-black/25 p-4 text-sm text-zinc-400 sm:grid-cols-3 xl:grid-cols-6">
          <StatusMetric label="Generated" value={summary.generated.toString()} />
          <StatusMetric label="Ready" value={summary.ready.toString()} />
          <StatusMetric label="Needs Work" value={summary.needsWork.toString()} />
          <StatusMetric label="Posted" value={summary.posted.toString()} />
          <StatusMetric label="Winners" value={summary.winners.toString()} />
          <StatusMetric label="Losers" value={summary.losers.toString()} />
        </section>

        <section className="flex flex-wrap gap-2 rounded-lg border border-white/10 bg-white/[0.03] p-3">
          {(["All", "Ready", "Needs Work", "Skip"] as const).map((item) => (
            <button
              key={item}
              type="button"
              onClick={() => setStatusFilter(item)}
              className={[
                "min-h-10 rounded-md px-3 text-xs font-black transition",
                statusFilter === item
                  ? "bg-white text-zinc-950"
                  : "border border-white/10 text-zinc-300 hover:bg-white/[0.06]",
              ].join(" ")}
            >
              {item}
            </button>
          ))}
          <div className="ml-auto min-h-10 rounded-md border border-white/10 px-3 py-2 text-xs font-bold text-zinc-400">
            Bulk copy: {platform} queue + full Markdown
          </div>
        </section>

        {copiedKey === "error" && (
          <div className="rounded-lg border border-yellow-300/30 bg-yellow-300/10 p-3 text-sm font-bold text-yellow-100">
            Clipboard blocked. Select the text and copy it manually.
          </div>
        )}

        <section className="grid gap-4">
          {visibleCards.map((card, index) => {
            const primary = card.assets.find(
              (asset) => asset.kind === selectedAssetKind,
            );
            const cardState = cardStates[card.record.id] || {
              clicks: 0,
              contentType: card.contentType,
              ctaStyle: card.ctaStyle,
              hookStyle: card.hookStyle,
              impressions: 0,
              improvementCount: 0,
              likes: 0,
              nextAngle: "",
              note: "",
              platform,
              posted: false,
              replies: 0,
              status: "",
              winner: "",
            };
            const performanceStatus = classifyPerformance(cardState);
            const canImprove = (cardState.improvementCount || 0) < 3;

            return (
              <article
                key={card.id}
                className="overflow-hidden rounded-lg border border-white/10 bg-zinc-900"
              >
                <div className="border-b border-white/10 bg-black/30 p-4">
                  <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
                    <div className="min-w-0">
                      <div className="text-xs font-black uppercase tracking-[0.14em] text-zinc-500">
                        Awareness {index + 1} / {card.record.sourceType} / {card.hookStyle}
                      </div>
                      <h2 className="mt-2 break-words text-xl font-black text-white">
                        {card.record.title}
                      </h2>
                      <p className="mt-2 max-w-4xl break-words text-sm leading-6 text-zinc-400">
                        {card.record.pain}
                      </p>
                    </div>
                    <button
                      type="button"
                      onClick={() =>
                        void handleCopy(
                          `${card.id}-primary`,
                          primary?.body || card.assets[0].body,
                        )
                      }
                      className="min-h-11 shrink-0 rounded-md bg-emerald-300 px-4 text-sm font-black text-zinc-950 transition hover:bg-emerald-200"
                    >
                      {copiedKey === `${card.id}-primary`
                        ? "Copied"
                        : `Copy ${platform}`}
                    </button>
                  </div>

                  <div className="mt-4 grid gap-3 lg:grid-cols-[1fr_auto]">
                    <QualityVerifier quality={card.quality} />
                    <div className="grid gap-2 sm:grid-cols-3 lg:w-72 lg:grid-cols-1">
                      <button
                        type="button"
                        disabled={!canImprove}
                        onClick={() => handleImprove(card)}
                        className={[
                          "min-h-10 rounded-md px-3 text-xs font-black transition",
                          canImprove
                            ? "bg-white text-zinc-950 hover:bg-zinc-200"
                            : "cursor-not-allowed border border-white/10 text-zinc-600",
                        ].join(" ")}
                      >
                        {canImprove
                          ? `Improve ${qualityLabels[card.quality.lowestField]}`
                          : "Improve limit reached"}
                      </button>
                      {performanceStatus === "winner" && (
                        <button
                          type="button"
                          onClick={() => handleMakeVariations(card)}
                          className="min-h-10 rounded-md bg-emerald-300 px-3 text-xs font-black text-zinc-950 transition hover:bg-emerald-200"
                        >
                          Make 3 Variations
                        </button>
                      )}
                      {performanceStatus === "loser" && (
                        <button
                          type="button"
                          onClick={() => handleRewriteHook(card)}
                          className="min-h-10 rounded-md border border-yellow-300/30 px-3 text-xs font-black text-yellow-100 transition hover:bg-yellow-300/10"
                        >
                          Rewrite Hook
                        </button>
                      )}
                    </div>
                  </div>

                  <div className="mt-4 grid gap-3 lg:grid-cols-[12rem_1fr]">
                    <label className="flex min-h-12 items-center gap-3 rounded-md border border-white/10 bg-white/[0.03] px-3 text-sm font-bold text-zinc-200">
                      <input
                        checked={cardState.posted}
                        onChange={(event) =>
                          updateCardState(card.record.id, {
                            posted: event.target.checked,
                          })
                        }
                        type="checkbox"
                        className="h-4 w-4 accent-emerald-300"
                      />
                      Posted
                    </label>
                    <textarea
                      aria-label={`Reaction note for ${card.record.title}`}
                      value={cardState.note}
                      onChange={(event) =>
                        updateCardState(card.record.id, {
                          note: event.target.value,
                        })
                      }
                      placeholder="Reaction note: replies, likes, objections, next angle..."
                      className="min-h-20 w-full rounded-md border border-white/10 bg-zinc-950 px-3 py-3 text-sm leading-6 text-zinc-100 outline-none transition placeholder:text-zinc-600 focus:border-emerald-300/60"
                    />
                  </div>

                  <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">
                    <MetricInput
                      label="Impressions"
                      value={cardState.impressions || 0}
                      onChange={(value) =>
                        updateCardState(card.record.id, {
                          impressions: value,
                          status: classifyPerformance({
                            ...cardState,
                            impressions: value,
                          }),
                        })
                      }
                    />
                    <MetricInput
                      label="Likes"
                      value={cardState.likes || 0}
                      onChange={(value) =>
                        updateCardState(card.record.id, {
                          likes: value,
                          status: classifyPerformance({ ...cardState, likes: value }),
                        })
                      }
                    />
                    <MetricInput
                      label="Replies"
                      value={cardState.replies || 0}
                      onChange={(value) =>
                        updateCardState(card.record.id, {
                          replies: value,
                          status: classifyPerformance({
                            ...cardState,
                            replies: value,
                          }),
                        })
                      }
                    />
                    <MetricInput
                      label="Clicks"
                      value={cardState.clicks || 0}
                      onChange={(value) =>
                        updateCardState(card.record.id, {
                          clicks: value,
                          status: classifyPerformance({ ...cardState, clicks: value }),
                        })
                      }
                    />
                    <label className="min-w-0">
                      <span className="text-xs font-black uppercase tracking-[0.14em] text-zinc-500">
                        Loop status
                      </span>
                      <select
                        value={performanceStatus}
                        onChange={(event) =>
                          updateCardState(card.record.id, {
                            status: event.target.value as PerformanceStatus,
                            winner: event.target.value as PerformanceStatus,
                          })
                        }
                        className="mt-1 min-h-10 w-full rounded-md border border-white/10 bg-zinc-950 px-3 text-sm font-bold text-zinc-100 outline-none"
                      >
                        <option value="">Unclassified</option>
                        <option value="winner">winner</option>
                        <option value="maybe">maybe</option>
                        <option value="loser">loser</option>
                      </select>
                    </label>
                  </div>

                  <textarea
                    aria-label={`Next angle for ${card.record.title}`}
                    value={cardState.nextAngle || ""}
                    onChange={(event) =>
                      updateCardState(card.record.id, {
                        nextAngle: event.target.value,
                      })
                    }
                    placeholder="Next angle: stronger buyer, sharper paid pain, different CTA..."
                    className="mt-3 min-h-14 w-full rounded-md border border-white/10 bg-zinc-950 px-3 py-3 text-sm leading-6 text-zinc-100 outline-none transition placeholder:text-zinc-600 focus:border-emerald-300/60"
                  />
                </div>

                <div className="grid gap-3 p-4 lg:grid-cols-2">
                  {card.assets.map((asset) => (
                    <AssetCard
                      key={`${card.id}-${asset.kind}`}
                      asset={asset}
                      copied={copiedKey === `${card.id}-${asset.kind}`}
                      highlighted={asset.kind === selectedAssetKind}
                      onCopy={() =>
                        void handleCopy(`${card.id}-${asset.kind}`, asset.body)
                      }
                    />
                  ))}
                </div>

                {(cardState.variations?.length || cardState.loserRewrite) && (
                  <div className="grid gap-3 border-t border-white/10 p-4 lg:grid-cols-2">
                    {cardState.variations?.map((variation, variationIndex) => (
                      <AssetCard
                        key={`${card.id}-variation-${variationIndex}`}
                        asset={{
                          body: variation,
                          kind: "X post",
                        }}
                        copied={
                          copiedKey === `${card.id}-variation-${variationIndex}`
                        }
                        highlighted
                        onCopy={() =>
                          void handleCopy(
                            `${card.id}-variation-${variationIndex}`,
                            variation,
                          )
                        }
                      />
                    ))}
                    {cardState.loserRewrite && (
                      <AssetCard
                        asset={{
                          body: cardState.loserRewrite,
                          kind: "X post",
                        }}
                        copied={copiedKey === `${card.id}-loser-rewrite`}
                        highlighted
                        onCopy={() =>
                          void handleCopy(
                            `${card.id}-loser-rewrite`,
                            cardState.loserRewrite || "",
                          )
                        }
                      />
                    )}
                  </div>
                )}
              </article>
            );
          })}
        </section>
      </div>
    </main>
  );
}

function ControlGroup({
  children,
  label,
}: {
  children: ReactNode;
  label: string;
}) {
  return (
    <div className="min-w-0">
      <div className="mb-2 text-xs font-black uppercase tracking-[0.14em] text-zinc-500">
        {label}
      </div>
      <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 xl:grid-cols-2 2xl:grid-cols-4">
        {children}
      </div>
    </div>
  );
}

function ToggleButton({
  active,
  label,
  onClick,
}: {
  active: boolean;
  label: string;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={[
        "min-h-11 rounded-md px-3 text-sm font-bold transition",
        active
          ? "bg-white text-zinc-950"
          : "border border-white/10 text-zinc-300 hover:bg-white/[0.06]",
      ].join(" ")}
    >
      {label}
    </button>
  );
}

function InfoPanel({ items, label }: { items: string[]; label: string }) {
  return (
    <div className="rounded-lg border border-white/10 bg-white/[0.03] p-3">
      <div className="text-xs font-black uppercase tracking-[0.14em] text-zinc-500">
        {label}
      </div>
      <div className="mt-2 flex flex-wrap gap-2">
        {items.map((item) => (
          <span
            key={item}
            className="rounded-md border border-white/10 px-2 py-1 text-xs font-bold text-zinc-300"
          >
            {item}
          </span>
        ))}
      </div>
    </div>
  );
}

function QualityVerifier({ quality }: { quality: QualityScores }) {
  return (
    <div className="rounded-lg border border-white/10 bg-white/[0.03] p-3">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <div className="text-xs font-black uppercase tracking-[0.14em] text-zinc-500">
            Content Quality Verifier
          </div>
          <div className="mt-1 text-sm font-black text-white">
            {quality.readiness} / Overall {quality.overall}
          </div>
        </div>
        <span
          className={[
            "w-fit rounded-md px-2 py-1 text-xs font-black",
            quality.readiness === "Ready"
              ? "bg-emerald-300 text-zinc-950"
              : quality.readiness === "Needs Work"
                ? "bg-yellow-300 text-zinc-950"
                : "bg-red-400 text-white",
          ].join(" ")}
        >
          {quality.readiness}
        </span>
      </div>
      <div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-5">
        <ScorePill label="Hook" value={quality.hook} />
        <ScorePill label="Buyer" value={quality.buyerSpecificity} />
        <ScorePill label="Paid pain" value={quality.paidPain} />
        <ScorePill label="Tiny offer" value={quality.tinyOffer} />
        <ScorePill label="CTA" value={quality.cta} />
      </div>
    </div>
  );
}

function ScorePill({ label, value }: { label: string; value: number }) {
  return (
    <div className="rounded-md border border-white/10 bg-black/20 px-3 py-2">
      <div className="text-[11px] font-black uppercase tracking-[0.12em] text-zinc-500">
        {label}
      </div>
      <div className="mt-1 text-sm font-black text-white">{value}/10</div>
    </div>
  );
}

function MetricInput({
  label,
  onChange,
  value,
}: {
  label: string;
  onChange: (value: number) => void;
  value: number;
}) {
  return (
    <label className="min-w-0">
      <span className="text-xs font-black uppercase tracking-[0.14em] text-zinc-500">
        {label}
      </span>
      <input
        min={0}
        onChange={(event) => onChange(Number(event.target.value) || 0)}
        type="number"
        value={value}
        className="mt-1 min-h-10 w-full rounded-md border border-white/10 bg-zinc-950 px-3 text-sm font-bold text-zinc-100 outline-none transition focus:border-emerald-300/60"
      />
    </label>
  );
}

function StatusMetric({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-md border border-white/10 bg-white/[0.03] p-3">
      <div className="text-xs font-black uppercase tracking-[0.14em] text-zinc-500">
        {label}
      </div>
      <div className="mt-1 text-lg font-black text-white">{value}</div>
    </div>
  );
}

function AssetCard({
  asset,
  copied,
  highlighted,
  onCopy,
}: {
  asset: GeneratedAsset;
  copied: boolean;
  highlighted: boolean;
  onCopy: () => void;
}) {
  return (
    <div
      className={[
        "min-w-0 rounded-lg border p-4",
        highlighted
          ? "border-emerald-300/50 bg-emerald-300/[0.06]"
          : "border-white/10 bg-black/25",
      ].join(" ")}
    >
      <div className="flex items-center justify-between gap-3">
        <h3 className="break-words text-sm font-black text-white">{asset.kind}</h3>
        <button
          type="button"
          onClick={onCopy}
          className="min-h-9 shrink-0 rounded-md border border-white/10 px-3 text-xs font-black text-zinc-100 transition hover:bg-white/[0.06]"
        >
          {copied ? "Copied" : "Copy"}
        </button>
      </div>
      <pre className="mt-4 max-h-72 whitespace-pre-wrap break-words font-sans text-sm leading-6 text-zinc-300">
        {asset.body}
      </pre>
    </div>
  );
}
